services:
  backend-baycanteen: 
    image: node:20-slim
    ports:
      - "40000:3000"
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - db
    restart: always

  db:
    image: postgres

    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    ports:
     - ${POSTGRES_PROD_PORT}:5432

    volumes:
      - baycanteen_postgres_data:/var/lib/postgresql/data

volumes:
  baycanteen_postgres_data: