services:
  baycanteen-db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PROD_PORT}:5432
    volumes:
      - app-volume:/var/lib/postgresql/data

  backend-baycanteen: 
    image: node:20-slim
    ports:
      - "40000:3000"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PROD_PORT=5432
    depends_on:
      - baycanteen-db
    env_file:
      - .env


    

volumes:
  app-volume: